### ISSUE TITLE
fortify `dplyr::rename`

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec.tidyverse#5]

**Comment by eoduniyi** [comment]
I will tackle this.

**Comment by eoduniyi** [comment]
> I will tackle this.

I've been trying to go through the documentation on hyperSpec and hyperSpec.tidyverse to make appropriate implementations, but I'm still lost on how to "fortify" dplyr methods. Or rather, I'm not sure I understand the nuances of the hyperSpec objects.  For example, for issue #5 I understand I need to implement `rename.hyperSpec`:

```{r}
# Case1: renaming an additional column
chondro %>% rename(region = clusters)
```

However, if `$spc` is renamed (I'm not sure why a user would rename spc though?), then I'm assuming the result is technically a data.frame and not a hyperSpec object:

```{r}
# Case2: renaming spc variable
chondro %>% rename(spc2 = spc) 
```

Following the `select.hyperSpec` example:
```{r}
  if (is.null(res$spc)){
    attr(res, "labels") <- labels(.data) 
    res
  }else{
    .data@data <- res
    labels (.data) <- labels(.data)[c ( ".wavelength", colnames(.data))]
    .data
  }
```
But I feel like that would be overkill because in  **Case2** nothing is being dropped, it's just the column name of the spectra has changed....

**Comment by cbeleites** [comment]
> I will tackle this.
@eoduniyi great, many thanks.

Case 1 describes the intended use, yes.

Case 2: I propose to not allow renaming of `$spc`. I.e. the attempt to rename `$spc` should lead to an error. 

- I fully agree that silently changing the class of the result is not a good idea for `rename()` since the overall columns do not change.
- A valid **hyperSpec** object must have a column `@data$spc`.   
You can use `chk.hy()` just before returning the result to verify that the result is a valid **hyperSpec** object, and this will throw an error if `@data$spc` is missing.
- There may be use cases where it makes sense to *copy* the spectra matrix into a new column (and then do things to that matrix). But that would be for  `mutate()` rather than `rename()`.

**Comment by eoduniyi** [comment]
`rename` for hypeSpec objects have been implemented. Going to close this now.
